[project]
name = "digital-designs"
version = "0.1.0"
description = "Digital Designs"
authors = []
requires-python = ">=3.13"
dependencies = [
  "atopile>=0.12.5",
  "bd-warehouse>=0.1.1",
  "build123d>=0.10.0",
  "jupyter>=1.1.1",
  "ocp-vscode>=3.0.1",
  "pint>=0.25.2",
  "svg-py>=1.10.0",
]

[dependency-groups]
dev = []
